In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import sklearn.metrics as metrics

import os, sys
import pandas as pd
import matplotlib.pyplot as plt

path_dat = "E:\OneDrive\Phys4501\data\RF_FI_GEO_OOS_CHAMP.hdf5"
path_dat = "C:/Users/murph/OneDrive/Phys4501/data/RF_FI_GEO_OOS_CHAMP.hdf5"
path_mod = os.path.normpath(os.getcwd()+'/../ml_fw/') # assumes current working directory is the ml_fw/Notebooks directory

# add the ml_fw module to Python Path and import what we need
sys.path.append(os.path.dirname(path_mod))

import ml_fw.inspect as inspect

In [2]:
dat = pd.read_hdf(path_dat)

dat['y_true'] = dat['400kmDensity'].copy()
dat['y_pred'] = dat['400kmDensity_pred'].copy()
dat['resid'] = dat['y_true']-dat['y_pred'] 

dat.head(1)
dat.describe()

,1300_02,43000_09,85550_13,94400_18,SYM_H index,AE,SatLat,cos_SatMagLT,sin_SatMagLT,cos_SatLon,sin_SatLon,400kmDensity,DateTime,storm,storm phase,400kmDensity_pred,y_true,y_pred,resid
105120,7.648391,10.081208,9.545769,9.306003,-5.0,23.0,43.7912,-0.58071,-0.81411,-0.036139,0.999347,3.659148,2003-01-01,1,2,4.227237,3.659148,4.227237,-0.568089

,1300_02,43000_09,85550_13,94400_18,SYM_H index,AE,SatLat,cos_SatMagLT,sin_SatMagLT,cos_SatLon,sin_SatLon,400kmDensity,storm,storm phase,400kmDensity_pred,y_true,y_pred,resid
count,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000
mean,7.125412,9.844823,9.427309,9.200223,-11.048346,173.185924,-0.086422,0.000377,-0.000026,-0.000815,-0.000038,1.329478,0.118978,0.458584,1.182700,1.329478,1.182700,0.146778
std,0.379437,0.210530,0.045686,0.253073,18.807064,211.903991,51.799981,0.710207,0.703993,0.707188,0.707026,1.195350,0.992898,1.344813,1.047223,1.195350,1.047223,0.406497
min,6.395051,9.715523,9.369749,9.147454,-488.000000,1.000000,-87.275300,-1.000000,-1.000000,-1.000000,-1.000000,0.000030,-1.000000,-1.000000,0.072221,0.000030,0.072221,-8.177295
25%,6.784116,9.760335,9.389104,9.160233,-17.000000,38.000000,-45.078040,-0.712492,-0.700972,-0.708521,-0.706551,0.544024,-1.000000,-1.000000,0.482997,0.544024,0.482997,-0.051803
50%,7.101278,9.818229,9.412996,9.183772,-8.000000,86.000000,-0.039010,0.000471,-0.000419,-0.001600,-0.000508,0.924439,1.000000,1.000000,0.814606,0.924439,0.814606,0.105469
75%,7.445087,9.909598,9.456292,9.224175,-1.000000,231.000000,45.039270,0.713630,0.701326,0.706804,0.706477,1.712489,1.000000,2.000000,1.532888,1.712489,1.532888,0.296264
max,9.525276,26.991252,9.717255,31.744619,92.000000,3529.000000,87.268960,1.000000,1.000000,1.000000,1.000000,25.004950,1.000000,2.000000,16.233193,25.004950,16.233193,14.799942

In [3]:
# large storm
sdate = '2005-08-21'
edate = '2005-08-30'

gd = (dat['DateTime'] > sdate) & (dat['DateTime'] <= edate)

rdat = dat[gd].copy()
rdat_id = rdat.index

met = lambda y_true, y_pred: metrics.median_absolute_error(y_true, y_pred)

In [27]:
w = {'window':'90min'}

In [28]:
t = rdat.set_index('DateTime').rolling(**w)

In [35]:
a = iter(t)

In [43]:
r_ind = [l for l in t]

In [46]:
r_ind[10]

,1300_02,43000_09,85550_13,94400_18,SYM_H index,AE,SatLat,cos_SatMagLT,sin_SatMagLT,cos_SatLon,sin_SatLon,400kmDensity,storm,storm phase,400kmDensity_pred,y_true,y_pred,resid,Metric,MedAE
DateTime,,,,,,,,,,,,,,,,,,,,
2005-08-21 00:05:00,7.437585,9.877268,9.442467,9.213179,21.0,49.0,62.88887,-0.998892,0.047054,0.455783,-0.890091,1.101933,-1,-1,1.326078,1.101933,1.326078,-0.224145,0.224145,0.224145
2005-08-21 00:10:00,7.437318,9.876968,9.442072,9.213015,21.0,47.0,81.19353,-0.950138,0.311829,-0.315486,0.948930,1.148601,-1,-1,1.305408,1.148601,1.305408,-0.156807,0.190476,0.190476
2005-08-21 00:15:00,7.437002,9.876580,9.441564,9.212804,22.0,48.0,77.84370,0.903182,0.429258,-0.975118,0.221688,0.751063,-1,-1,0.784328,0.751063,0.784328,-0.033266,0.156807,0.156807
2005-08-21 00:20:00,7.436950,9.876500,9.441445,9.212760,22.0,47.0,60.07045,0.978554,0.205991,0.013553,-0.999908,0.715237,-1,-1,0.647447,0.715237,0.647447,0.067790,0.112298,0.112298
2005-08-21 00:25:00,7.437278,9.876887,9.441919,9.212968,23.0,48.0,38.82546,0.989436,0.144969,0.321353,-0.946960,0.557800,-1,-1,0.574326,0.557800,0.574326,-0.016526,0.067790,0.067790
2005-08-21 00:30:00,7.437177,9.876753,9.441732,9.212895,24.0,47.0,20.43119,0.991026,0.133666,0.324504,-0.945884,0.415018,-1,-1,0.547459,0.415018,0.547459,-0.132440,0.100115,0.100115
2005-08-21 00:35:00,7.437225,9.876797,9.441771,9.212917,24.0,44.0,0.02130,0.993752,0.111608,0.254930,-0.966959,0.547655,-1,-1,0.541906,0.547655,0.541906,0.005749,0.067790,0.067790
2005-08-21 00:40:00,7.437438,9.877035,9.442055,9.213045,25.0,49.0,-21.02436,0.999122,0.041902,0.182109,-0.983278,0.431746,-1,-1,0.567897,0.431746,0.567897,-0.136151,0.100115,0.100115
2005-08-21 00:45:00,7.438045,9.877679,9.442847,9.213393,25.0,48.0,-39.03666,0.999161,-0.040960,0.186720,-0.982413,0.401179,-1,-1,0.556402,0.401179,0.556402,-0.155223,0.132440,0.132440
2005-08-21 00:50:00,7.437979,9.877603,9.442734,9.213350,25.0,46.0,-60.18740,0.991652,-0.128943,0.482036,-0.876152,0.398173,-1,-1,0.581564,0.398173,0.581564,-0.183392,0.134296,0.134296
2005-08-21 00:55:00,7.438373,9.877985,9.443194,9.213556,26.0,48.0,-78.17957,0.967968,-0.251073,0.675914,0.736981,0.438443,-1,-1,0.734746,0.438443,0.734746,-0.296304,0.136151,0.136151

In [7]:
rdat['Metric'] = [met(rdat.set_index('DateTime').loc[l.index,'y_true'],rdat.set_index('DateTime').loc[l.index,'y_pred']) for l in t]

In [ ]:
rdat_id

In [8]:
rdat['MedAE'] = rdat.set_index('DateTime')['resid'].abs().rolling('90min').median().reset_index().drop(columns='DateTime').set_index(rdat.index)

In [9]:
rdat.tail()

,1300_02,43000_09,85550_13,94400_18,SYM_H index,AE,SatLat,cos_SatMagLT,sin_SatMagLT,cos_SatLon,...,400kmDensity,DateTime,storm,storm phase,400kmDensity_pred,y_true,y_pred,resid,Metric,MedAE
385052,7.328291,9.901606,9.457507,9.221882,-5.0,42.0,66.19498,0.999907,0.013639,-0.859128,...,1.118123,2005-08-29 23:40:00,1,1,1.096015,1.118123,1.096015,0.022108,0.085077,0.085077
385053,7.328188,9.901579,9.457501,9.221863,-4.0,40.0,47.93769,0.997011,-0.077258,-0.485276,...,0.906444,2005-08-29 23:45:00,1,1,0.843016,0.906444,0.843016,0.063429,0.085077,0.085077
385054,7.327556,9.901196,9.457045,9.221644,-4.0,41.0,27.27564,0.994356,-0.106091,-0.413615,...,0.658908,2005-08-29 23:50:00,1,1,0.805370,0.658908,0.805370,-0.146462,0.100033,0.100033
385055,7.326923,9.900783,9.456549,9.221409,-4.0,42.0,9.17768,0.992362,-0.123359,-0.456175,...,0.741683,2005-08-29 23:55:00,1,1,0.818186,0.741683,0.818186,-0.076503,0.100033,0.100033
385056,7.292541,9.886229,9.446570,9.212852,-5.0,41.0,-10.57332,0.985132,-0.171800,-0.524849,...,0.775622,2005-08-30 00:00:00,1,1,0.912272,0.775622,0.912272,-0.136650,0.120873,0.120873

In [ ]:
a = rdat.set_index('DateTime').index.name
a

In [41]:
if not a:
    print('hi')

In [86]:
a = dat['DateTime'].dtype.type

In [ ]:
isinstance(a, pd.DatetimeTZDtype)

In [ ]:
from pandas.api.types import is_datetime64_any_dtype as is_datetime

is_datetime(dat['DateTime'])

In [93]:
roll_kwargs = {'window':'60min', 'center':True}

In [ ]:
if 'window' in roll_kwargs:
    print('hi')

In [ ]:
np.issubdtype(dat['storm'].dtype, np.integer)

In [48]:
a = rdat.set_index('DateTime')['resid'].abs().rolling('90min').median().index

In [49]:
ff = pd.DataFrame({'DateTime':a, 'Metric':rdat['Metric'].values})

In [50]:
ff

                DateTime    Metric
0    2005-08-21 00:05:00  0.224145
1    2005-08-21 00:10:00  0.190476
2    2005-08-21 00:15:00  0.156807
3    2005-08-21 00:20:00  0.112298
4    2005-08-21 00:25:00  0.067790
...                  ...       ...
2587 2005-08-29 23:40:00  0.085077
2588 2005-08-29 23:45:00  0.085077
2589 2005-08-29 23:50:00  0.100033
2590 2005-08-29 23:55:00  0.100033
2591 2005-08-30 00:00:00  0.120873

[2592 rows x 2 columns]