In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import sklearn.metrics as metrics

import os, sys
import pandas as pd
import matplotlib.pyplot as plt

path_dat = "E:\OneDrive\Phys4501\data\RF_FI_GEO_OOS_CHAMP.hdf5"
path_mod = os.path.normpath(os.getcwd()+'/../ml_fw/') # assumes current working directory is the ml_fw/Notebooks directory

# add the ml_fw module to Python Path and import what we need
sys.path.append(os.path.dirname(path_mod))

import ml_fw.inspect as inspect

In [61]:
dat = pd.read_hdf(path_dat)

dat['y_true'] = dat['400kmDensity'].copy()
dat['y_pred'] = dat['400kmDensity_pred'].copy()
dat = dat.set_index('DateTime')

dat.head(1)
dat.describe()

,1300_02,43000_09,85550_13,94400_18,SYM_H index,AE,SatLat,cos_SatMagLT,sin_SatMagLT,cos_SatLon,sin_SatLon,400kmDensity,storm,storm phase,400kmDensity_pred,y_true,y_pred
DateTime,,,,,,,,,,,,,,,,,
2003-01-01,7.648391,10.081208,9.545769,9.306003,-5.0,23.0,43.7912,-0.58071,-0.81411,-0.036139,0.999347,3.659148,1,2,4.227237,3.659148,4.227237

,1300_02,43000_09,85550_13,94400_18,SYM_H index,AE,SatLat,cos_SatMagLT,sin_SatMagLT,cos_SatLon,sin_SatLon,400kmDensity,storm,storm phase,400kmDensity_pred,y_true,y_pred
count,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000,790123.000000
mean,7.125412,9.844823,9.427309,9.200223,-11.048346,173.185924,-0.086422,0.000377,-0.000026,-0.000815,-0.000038,1.329478,0.118978,0.458584,1.182700,1.329478,1.182700
std,0.379437,0.210530,0.045686,0.253073,18.807064,211.903991,51.799981,0.710207,0.703993,0.707188,0.707026,1.195350,0.992898,1.344813,1.047223,1.195350,1.047223
min,6.395051,9.715523,9.369749,9.147454,-488.000000,1.000000,-87.275300,-1.000000,-1.000000,-1.000000,-1.000000,0.000030,-1.000000,-1.000000,0.072221,0.000030,0.072221
25%,6.784116,9.760335,9.389104,9.160233,-17.000000,38.000000,-45.078040,-0.712492,-0.700972,-0.708521,-0.706551,0.544024,-1.000000,-1.000000,0.482997,0.544024,0.482997
50%,7.101278,9.818229,9.412996,9.183772,-8.000000,86.000000,-0.039010,0.000471,-0.000419,-0.001600,-0.000508,0.924439,1.000000,1.000000,0.814606,0.924439,0.814606
75%,7.445087,9.909598,9.456292,9.224175,-1.000000,231.000000,45.039270,0.713630,0.701326,0.706804,0.706477,1.712489,1.000000,2.000000,1.532888,1.712489,1.532888
max,9.525276,26.991252,9.717255,31.744619,92.000000,3529.000000,87.268960,1.000000,1.000000,1.000000,1.000000,25.004950,1.000000,2.000000,16.233193,25.004950,16.233193

In [31]:
met = lambda y_true, y_pred: metrics.median_absolute_error(y_true, y_pred)

In [66]:
dat.y_true

DateTime
2003-01-01 00:00:00    3.659148
2003-01-01 00:05:00    4.745748
2003-01-01 00:10:00    5.470819
2003-01-01 00:15:00    5.239831
2003-01-01 00:20:00    5.050540
                         ...
2010-09-03 23:40:00    0.435259
2010-09-03 23:45:00    0.405432
2010-09-03 23:50:00    0.451866
2010-09-03 23:55:00    0.560700
2010-09-04 00:00:00    0.784108
Name: y_true, Length: 790123, dtype: float64

In [104]:
def masscenter(ser, x, y):   
    return met(x,y)

In [90]:
dat[['y_true','y_pred']].values.shape

(790123, 2)

In [119]:
a = dat.iloc[0:1000][['y_true']].rolling('90min').apply(masscenter, raw=True)

In [120]:
a

                       y_true
DateTime
2003-01-01 00:00:00  0.187433
2003-01-01 00:05:00  0.187433
2003-01-01 00:10:00  0.187433
2003-01-01 00:15:00  0.187433
2003-01-01 00:20:00  0.187433
...                       ...
2003-01-04 10:55:00  0.187433
2003-01-04 11:00:00  0.187433
2003-01-04 11:05:00  0.187433
2003-01-04 11:10:00  0.187433
2003-01-04 11:15:00  0.187433

[1000 rows x 1 columns]